Landing main
YeaHubTeam/yeahub-landing pull request #10
Opened 2024-04-27 17:45 UTC by ArturSha

Добавил бесконечный слайдер, с адаптивом. так же добавил хук useObserve

2024-04-28 07:01 UTC, Buffik commented on src/widgets/FeedbackBlock/ui/FeedbackBlock.tsx
>  export const FeedbackBlock = memo(() => {
и всё-таки я против memo в лэндинге, нечего тут мемоизировать, на мой взгляд. @PerelomaDenis Можешь прокомментировать, пожалуйста?

Также нужно что-то сделать с декомпозицией, слишком сложный компонент. Возможно получится вынести логику? Как только меняется isVisible, всё внутри ререндерится

2024-04-28 08:06 UTC, ArturSha commented on src/widgets/FeedbackBlock/ui/FeedbackBlock.tsx
> +	const isVisible: boolean = useObserver(sliderRef);
Опшенс вынес, но тянут библиотеку ради маленького лендинга не очень хочется. Обсервер у нас тут в 2х местах только, у меня в блоке с слайдером и у тебя , там где нужно будет перехватить скрол ?

2024-04-28 08:29 UTC, ArturSha commented on src/widgets/FeedbackBlock/ui/FeedbackBlock.tsx
>  export const FeedbackBlock = memo(() => {
тут согласен, это я по привычке развернул снипетом, т.к. тут нету пропсов, тут мемо не нужно, т.к. ему нечего отслеживать

2024-04-28 11:41 UTC, ArturSha commented on src/widgets/FeedbackBlock/ui/FeedbackBlock.tsx
> +				</Button>
![image](https://github.com/YeaHubTeam/yeahub-landing/assets/108091184/01094527-8331-4f96-a133-b277fe57e400)
если посмотреть код , то вроде все отцентровано. да и мне вроде в глаза ничего не бросается, нужно еще мнение ) желательно дизайнеров )

2024-04-28 11:51 UTC, ArturSha reviewed
убрал мемоизацию с блоков. вынес настройки обсервера.

2024-04-29 10:10 UTC, MirgradR commented on src/shared/libs/makeCarouselInfinite/makeCarouselInfinite.ts
> +export const makeCarouselInfinite = (
https://doka.guide/js/array-to-spliced/
новый метод

2024-04-29 12:11 UTC, PerelomaDenis requested changes

2024-04-29 12:11 UTC, PerelomaDenis commented on src/widgets/FeedbackBlock/ui/FeedbackBlock.tsx
> +	const isVisible: boolean = useObserver(sliderRef);
Я тоже думаю, что нет смысла тащить либу. Но стоит из FeedbackBlock всю логику, связанную со слайдером отдельно вынести. Предлагаю вынести jsx с кнопками и мапингом массива(сам массив конечно же принимать пропсами) в компонент shared/Slider/ui/. А логику вынести в тот же компонент, так как по сути эта логика относится только к слайдеру в shared/Slider/model/utils

2024-04-29 12:11 UTC, PerelomaDenis commented on src/shared/libs/useObserver/useObserver.tsx
> +				if (entry.isIntersecting) {
тут можно упростить написав просто setIsVisible(entry.isIntersecting)

2024-04-29 12:11 UTC, PerelomaDenis commented on src/shared/libs/useObserver/useObserver.tsx
> +import { RefObject, useEffect, useState } from 'react';
Под хуки лучше создать в папке shared/libs отдельную папку hooks. А для каких то утилит - utils

2024-05-01 19:55 UTC, ArturSha commented on src/shared/libs/useObserver/useObserver.tsx
> +				if (entry.isIntersecting) {
исправил

2024-05-05 18:21 UTC, Buffik approved these changes

2024-05-05 18:37 UTC, PerelomaDenis approved these changes

2024-05-05 18:39 UTC, merged