YH-124: add uathorization logic
YeaHubTeam/yeahub-landing pull request #16
Opened 2024-05-16 19:02 UTC by Buffik

Добавил логику аутентификации, пока без логики рефреша токена, так как сервер выдает ошибку

2024-05-16 19:28 UTC, PerelomaDenis requested changes

2024-05-16 19:28 UTC, PerelomaDenis commented on src/features/authentication/login/model/types/authentication.ts
>  export interface Authentication {
Переименуй файл как login.ts и переименуй название интерфейса в Login

2024-05-16 19:28 UTC, PerelomaDenis commented on src/features/authentication/login/ui/LoginForm/LoginForm.tsx
> +	const { handleSubmit } = useFormContext<LoginSchema>();
Чуть ниже ты уже используешь useFormContext, соедини оба в один

2024-05-16 19:28 UTC, PerelomaDenis commented on src/features/authentication/login/ui/LoginForm/LoginForm.tsx
> +	useEffect(() => {
давай заменим useEffect на такую конструкцию. И наверное стоит в catch записывать в стейт текст ошибки и выводить под формой где нить
![image](https://github.com/YeaHubTeam/yeahub-landing/assets/88330372/791bf1b2-e13e-46d3-9dd9-ed2fbdecb27e)

2024-05-16 19:28 UTC, PerelomaDenis commented on src/pages/LoginPage/model/slices/loginPageSlice.ts
> +		access_token: localStorage.getItem('accessToken') || '',
Давай лучше через camelCase писать

2024-05-16 19:28 UTC, PerelomaDenis commented on src/pages/LoginPage/model/slices/loginPageSlice.ts
> +import { createSlice, PayloadAction } from '@reduxjs/toolkit';
Я думаю логичней, чтобы этот слайс был не здесь, а в сущности user например. 
То всю папку model засунь в сущность user
И я что-то не нашел где у тебя используется setUserData. После запроса на логин просто делается редирект без записи токена

2024-05-18 14:08 UTC, PerelomaDenis requested changes

2024-05-18 14:08 UTC, PerelomaDenis commented on src/shared/ui/ErrorMessageRenderer/ErrorMessageRenderer.tsx
> +	return <div className={styles.wrapper}>Что-то пошло не так! Статус-код ошибки: {props}</div>;
Может не стоит создавать под это отдельную компоненту. Это ж просто текст, и у нас в сторибуке есть компонент текста с красным цветом

2024-05-18 14:29 UTC, Buffik commented on src/features/authentication/login/ui/LoginForm/LoginForm.tsx
> +				dispatch(loginPageActions.catchError(error.status));
Поправлю после того, как сделают возвращаемые ошибки

2024-05-18 15:37 UTC, PerelomaDenis approved these changes

2024-05-18 15:42 UTC, merged